# File: azure-pipelines.yml
trigger: none

resources:
 repositories:
 - repository: test
   name: test
   type: github
   endpoint: devops7997

extends:
  template: simple-param.yml
  parameters:
      yesNo: false # set to a non-boolean value to have the build fail
