# File: simple-param.yml test test
parameters: 
- name: yesNo # name of the parameter; required
  type: boolean # data type of the parameter; required
  default: false

jobs:
- job: myJob
  timeoutInMinutes: 10
  pool:
    name: test
  steps:
  - bash: echo "Hello world"
